### ISSUE TITLE
cannot find 'hammer-v0_dapg'

### ISSUE THREAD

**Issue by xiaoqingyu0113** [YanjieZe/H-InDex#1]
Hello,

**When I'm trying to run the following command for training,** 

$ bash scripts/adroit/train.sh hammer-v0 hindex test 0 0

**I have  the following error:**

Cannot find primary config 'hammer-v0_dapg'. Check that it's in your config search path.

Config search path:
	provider=vc_models-plugin, path=pkg://vc_models.conf
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///home/qingyu/H-InDex/stage3_RL/examples/config/adroit
	provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by YanjieZe** [comment]
sorry for the wrong command provided in README.md! Could you try to change `hammer-v0` to `hammer` and see whether it works?

**Comment by xiaoqingyu0113** [comment]
Works pretty well! Thanks a lot for your quick response!
